import json
import threading
from typing import Any, Callable, Dict, List, Optional

import dspy

_file_lock = threading.Lock()


def log_self_correction_example(
    dataset_log_path: str,
    inputs: Dict[str, Any],
    outputs: Dict[str, Any],
    redact_hook: Optional[Callable[[Dict[str, Any]], Optional[Dict[str, Any]]]] = None,
) -> None:
    """
    Safely merges inputs and outputs, applies redact_hook if provided, and appends
    the resulting example as a JSON line to dataset_log_path.
    """
    example_dict = {**inputs, **outputs}
    if redact_hook is not None:
        try:
            res = redact_hook(example_dict)
            if res is None:
                return
            example_dict = res
        except Exception:
            return

    try:
        line = json.dumps(example_dict, ensure_ascii=False)
    except Exception:
        return

    with _file_lock:
        try:
            with open(dataset_log_path, "a", encoding="utf-8") as f:
                f.write(line + "\n")
        except Exception:
            pass


def load_logged_dataset(
    dataset_log_path: str,
    input_keys: List[str],
) -> List[dspy.Example]:
    """
    Loads a JSONL file generated by self-correction logging and returns it
    as a list of dspy.Example objects ready for DSPy teleprompters.
    """
    examples = []
    try:
        with open(dataset_log_path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    data = json.loads(line)
                    example = dspy.Example(**data).with_inputs(*input_keys)
                    examples.append(example)
                except Exception:
                    continue
    except Exception:
        pass
    return examples
